/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Cookie.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct returnStatus *
getmemycookie_1(argp, clnt)
	param *argp;
	CLIENT *clnt;
{
	static struct returnStatus clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GETMEMYCOOKIE, xdr_param, argp, xdr_returnStatus, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
