/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COOKIE_H_RPCGEN
#define _COOKIE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct param {
	int userId;
};
typedef struct param param;
#ifdef __cplusplus
extern "C" bool_t xdr_param(XDR *, param*);
#elif __STDC__
extern  bool_t xdr_param(XDR *, param*);
#else /* Old Style C */
bool_t xdr_param();
#endif /* Old Style C */


struct returnStatus {
	int cookieStatus;
};
typedef struct returnStatus returnStatus;
#ifdef __cplusplus
extern "C" bool_t xdr_returnStatus(XDR *, returnStatus*);
#elif __STDC__
extern  bool_t xdr_returnStatus(XDR *, returnStatus*);
#else /* Old Style C */
bool_t xdr_returnStatus();
#endif /* Old Style C */


#define MESSAGE_BOARD ((rpc_uint)0x83526175)
#define MESSAGE_BOARD_VERSION ((rpc_uint)1)

#ifdef __cplusplus
#define GETMEMYCOOKIE ((rpc_uint)1)
extern "C" struct returnStatus * getmemycookie_1(param *, CLIENT *);
extern "C" struct returnStatus * getmemycookie_1_svc(param *, struct svc_req *);

#elif __STDC__
#define GETMEMYCOOKIE ((rpc_uint)1)
extern  struct returnStatus * getmemycookie_1(param *, CLIENT *);
extern  struct returnStatus * getmemycookie_1_svc(param *, struct svc_req *);

#else /* Old Style C */
#define GETMEMYCOOKIE ((rpc_uint)1)
extern  struct returnStatus * getmemycookie_1();
extern  struct returnStatus * getmemycookie_1_svc();
#endif /* Old Style C */

#endif /* !_COOKIE_H_RPCGEN */
