/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Cookie.h"

bool_t
xdr_param(xdrs, objp)
	XDR *xdrs;
	param *objp;
{

	if (!xdr_int(xdrs, &objp->userId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_returnStatus(xdrs, objp)
	XDR *xdrs;
	returnStatus *objp;
{

	if (!xdr_int(xdrs, &objp->cookieStatus))
		return (FALSE);
	return (TRUE);
}
